version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_task_manager
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
      POSTGRES_DB: ${DB_NAME:-task-manager-db}
    ports:
      - "5432:5432"
    networks:
      - project-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend_task_manager
    restart: always
    ports:
      - "5228:5228"
    environment:
      ConnectionStrings__DefaultConnection: "Host=${DB_HOST:-postgres};Port=${DB_PORT:-5432};Database=${DB_NAME:-task-manager-db};Username=${DB_USER:-postgres};Password=${DB_PASS:-postgres}"
      ASPNETCORE_URLS: "http://0.0.0.0:5228"
    depends_on:
      - postgres
    networks:
      - project-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:5228
    container_name: frontend_task_manager
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - project-network

volumes:
  postgres_data:

networks:
  project-network:
    driver: bridge
