services:
  postgres:
    image: postgres:15
    container_name: postgres_task_manager
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task-manager-db
    ports:
      - "5432:5432"
    networks:
      - project-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  project-network:
    driver: bridge